---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-deployment
spec:
  selector:
    matchLabels:
      app: test1
  replicas: 1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - image: jasperjiang/service-a:4
        imagePullPolicy: Always
        name: test1
        readinessProbe:
          exec:
            command:
              - date
          initialDelaySeconds: 60
