---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  selector:
    matchLabels:
      app: test2
  replicas: 1
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - image: jasperjiang/service-b:4
        imagePullPolicy: Always
        name: test2
